### ISSUE TITLE
UART and RTT not working on Bluepill with NRF52

### ISSUE THREAD

**Issue by TheyCallMeNobody** [blackmagic-debug/blackmagic#1396]
Hello, I have an nrf52840 chip with two firmware versions. One is printing Debug Output over UART and the other one over RTT.
The UART output works fine with an external UART to USB adapter and also RTT works over my nrf52840 dev kit. Flashing the chip over SWD with blackmagic works fine, but it isn't able to find the RTT Control Block.
As Probe I'm using a bluepill board, where the UART output of the NRF Chip is connected to Pin B7.
Also over UART only the blackmagic debug strings are printed, but not the Debug Messages from my NRF Chip

**Comment by koendv** [comment]
Try
(gdb) mon rtt ram 0x20000000 0x20002000

**Comment by TheyCallMeNobody** [comment]
Hi, thanks for your answer.
I've figured out the first problem, which was that I was trying to use gdb and not arm-none-eabi-gdb.
With using the correct one, UART is now working. I have now the problem, that after attaching and an initial continue command, the nrf seems to run fine, until it suddenly runs into: "Program received signal SIGSEGV, Segmentation fault.".
Without using the debugger, the software runs normal without crashing. I should add here, that I use the Nordic softdevice in my firmware. I tried using the gdb non-stop function, because I thought, that it may interrupt something timing critical, but with this option enabled, I can't even connect to the chip: Attaching to Remote target failed with: T05thread:1;

**Comment by dragonmux** [comment]
GDB's non-stop mode is not currently supported. Perigoso has an experimental patch in PR #1361 which you might be interested in giving a try.

**Comment by perigoso** [comment]
@dragonmux actually, that patch doesn't really try implement non-stop mode, just a no-acknowledgment mode, and though I think this is required for the former, it's not quite tied to it, GDB will still block waiting for a response

**Comment by dragonmux** [comment]
Ah, good to know! Then yeah, we don't currently support non-stop mode which is why that fails for TheCallMeNobody

**Comment by jbussmann** [comment]
> I have now the problem, that after attaching and an initial continue command, the nrf seems to run fine, until it suddenly runs into: "Program received signal SIGSEGV, Segmentation fault.". Without using the debugger, the software runs normal without crashing. I should add here, that I use the Nordic softdevice in my firmware.

Are you getting the segmentation fault out of the blue? I always get segmentation faults wehen trying to resume after hitting a beakpoint and accepted this answer form [here](https://devzone.nordicsemi.com/f/nordic-q-a/477/can-i-debug-ble-program) as valid explanation:

> You are right that when you start the CPU after having been halted on a breakpoint, you'll most likely either see an assert or hang in an infinite loop. </br>
The reason is simply that the nRF51822 only have a single processor, so both the application and the softdevice's BLE stack will be halted when the device halts on a breakpoint. It is therefore not possible for the softdevice to receive or transmit BLE packages while halted, and this means that BLE link will be considered lost after the connection supervision timeout. Also, all stack events and hardware interrupts occurring will not be received properly while halted, so if you start running again, the internal sanity checks in the softdevice will therefore most likely fail, causing an assert. </br>
You therefore have to do debugging by other means when using the softdevice, for example by doing UART printouts, toggling GPIO or similar. Please also note that it's perfectly possible to halt the CPU on a certain condition and look at the current state of variables and similar, it's only if you try to start again that you will see problems.

**Comment by dragonmux** [comment]
👋🏼 Going back through open bugs on the tracker and was wondering if this is still an issue with the latest release firmware or if this is now fixed?

**Comment by TheyCallMeNobody** [comment]
Hello,
unfortunately I can't remember exactly if I got RTT working correctly. I think one of the main problems was that blackmagic stopped all threads as explained in @jbussmann post. But I think this issue can be closed,. I currently can't test if these problems still exist, because I don't have the hardware set up like I had a year ago. If I find some time I can try it out and may open a issue again but this may take a while
