### ISSUE TITLE
BMDA Cannot Find Segger J-Link Probes

### ISSUE THREAD

**Issue by rhempel** [blackmagic-debug/blackmagic#1939]
I have built BMDA for Windows 11 using the mingw32-make step from main branch:

It finds and connects to ST-Link devices with no issues.

I have an NRF52 dev board and an older J-Link that work correctly with J-Link drivers and software under Windows and Linux.

Running BMDA we get this for the classic J-Link:

```
blackmagic.exe -v 63
No probes found
```

For the NRF52 dev board with the J-Link embedded on the board and enumerated as COM43 we get:

```
>blackmagic.exe -v 63 -d COM43
Black Magic Debug App v1.10.0-1225-ga1dd3f6d
 for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, J-Link and FTDI (MPSSE)
+#!GA#
Timeout while waiting for BMP response
Remote Start failed, error
```

**Comment by dragonmux** [comment]
You need to use Zadig to rebind your J-Link from their proprietary driver to WinUSB. This is a problem unique to Windows.

J-Link dongles do not talk the BMD remote protocol which is why using `-d` like that isn't going to work - this command line option exists purely for forcing things with BMPs and has close to no usefulness in general usage and cannot be used with any other kinds of dongle (ST-Link, CMSIS-DAP, J-Link).
